# built with Flutter 2.10.5
name: icards
description: A new Flutter project.
version: 1.0.2+4

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^2.0.0-nullsafety.0     # simple state management
  tuple: ^2.0.0                         # tuples support
  http: ^0.13.5                         # http support
  html: ^0.15.0                         # html support
  fluttertoast: ^8.0.9                  # toast messages

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
